### ISSUE TITLE
HeatMap Doesn't Work

### ISSUE THREAD

**Issue by g0dfather** [rvspt/GoogleMapsAPIv3Toolkit-QV#2]
The heatmap of this extension does not work within my own project nor the attached example application file.

**Comment by rvspt** [comment]
Hum, could you elaborate more details about your environment? Works without incident in my environment. I am using QV12, but it was developed and tested with QV11.2.

**Comment by g0dfather** [comment]
Hi Renato,

My problems are in relation to the Qliksense version of the extension. I am using Qliksense 2.05 and on internet explorer 11. I'm beginning to feel it could be a setting issue on the internet explorer browser. Have you stumbled across a similar issue before?

Thanks,

Clayton

**Comment by rvspt** [comment]
Hello Clayton, 

This is the QlikView repository, not Qlik Sense https://github.com/rvspt/GoogleMapsAPIv3Toolkit-QS, we should continue this issue in its proper place ;)

I tested in Qlik Sense v3 and IE 11 under Windows 10, all working fine. The extension was developed at the time using v2, which makes me believe your suspicion related to your IE can be correct. Could you test with another browser and let me know. Also, are you using Qlik Sense Desktop or Server?

I'll close the issue here and wait for your comment in the repository for Qlik Sense version.

Cheers!
